### ISSUE TITLE
first character on line 3 is a semi-colon

### ISSUE THREAD

**Issue by moloko** [cgkineo/jquery.imageready#1]
it doesn't seem to be causing a problem, but it is right that the first character on line 3 is a semi-colon?

**Comment by oliverfoster** [comment]
It's there intentionally, just to finish off any previous line.

**Comment by oliverfoster** [comment]
It's there intentionally, just to finish off any previous line.

**Comment by moloko** [comment]
fair enough! feel free to close this now ;-)

**Comment by oliverfoster** [comment]
Cool. yea... wrong button tssh!
